"""
v2.0 Core Models for Intelligent Multi-Agent Orchestration.

Key design principles:
- DAG-based execution: Agent tasks are nodes in a directed acyclic graph
- Capability registry: Orchestrator discovers agents through registration, not hardcoding
- Dynamic planning: Orchestrator Agent generates DAGs at runtime via LLM
- Context isolation: Each agent has independent context, handoff via artifacts
"""

from __future__ import annotations

import uuid
from datetime import datetime
from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, Field


class AgentCapability(BaseModel):
    """
    Description of a Worker Agent's capabilities.
    Registered in AgentRegistry, consumed by IntelligentOrchestrator.
    """
    id: str
    name: str
    description: str
    skills: list[str] = Field(default_factory=list)
    input_schema: list[str] = Field(default_factory=list)
    output_schema: list[str] = Field(default_factory=list)
    constraints: list[str] = Field(default_factory=list)
    system_prompt: str = ""  # Optional custom system prompt for this agent


class NodeStatus(str, Enum):
    """Execution status of a DAG node."""
    PENDING = "pending"
    RUNNING = "running"
    SUCCESS = "success"
    FAILED = "failed"
    SKIPPED = "skipped"
    RETRYING = "retrying"


class DAGNode(BaseModel):
    """
    A single node in the execution DAG = one agent task.
    """
    id: str
    agent_type: str           # References AgentCapability.id
    task_description: str
    status: NodeStatus = NodeStatus.PENDING
    result: dict[str, Any] = Field(default_factory=dict)
    error: str = ""
    output_artifacts: list[str] = Field(default_factory=list)
    max_retries: int = 3
    retry_count: int = 0
    started_at: datetime | None = None
    completed_at: datetime | None = None

    def model_post_init(self, __context: Any) -> None:
        if not self.id:
            self.id = f"node_{uuid.uuid4().hex[:8]}"


class DAGEdge(BaseModel):
    """A directed edge from one node to another."""
    from_node: str
    to_node: str


class DAG(BaseModel):
    """
    Directed Acyclic Graph = execution plan.
    Generated by IntelligentOrchestrator, executed by DAGExecutionEngine.
    """
    nodes: dict[str, DAGNode] = Field(default_factory=dict)
    edges: list[DAGEdge] = Field(default_factory=list)
    reasoning: str = ""  # Orchestrator's reasoning for this plan

    def add_node(self, node: DAGNode) -> None:
        self.nodes[node.id] = node

    def add_edge(self, from_id: str, to_id: str) -> None:
        self.edges.append(DAGEdge(from_node=from_id, to_node=to_id))

    def get_dependencies(self, node_id: str) -> list[str]:
        """Get all predecessor nodes."""
        return [e.from_node for e in self.edges if e.to_node == node_id]

    def get_dependents(self, node_id: str) -> list[str]:
        """Get all successor nodes."""
        return [e.to_node for e in self.edges if e.from_node == node_id]

    def topological_levels(self) -> list[list[str]]:
        """
        Return topological sort as levels.
        Nodes in the same level have no dependencies between each other
        and can be executed in parallel.
        """
        in_degree = {nid: 0 for nid in self.nodes}
        adj = {nid: [] for nid in self.nodes}

        for edge in self.edges:
            adj[edge.from_node].append(edge.to_node)
            in_degree[edge.to_node] += 1

        levels = []
        remaining = set(self.nodes.keys())

        while remaining:
            # Find all nodes with in-degree 0
            current_level = [
                nid for nid in remaining
                if in_degree[nid] == 0
            ]
            if not current_level:
                raise ValueError("Cycle detected in DAG")

            levels.append(current_level)
            remaining -= set(current_level)

            # Remove current level from graph
            for nid in current_level:
                for dependent in adj[nid]:
                    in_degree[dependent] -= 1

        return levels

    def get_ready_nodes(self) -> list[str]:
        """Get nodes whose dependencies are all satisfied."""
        ready = []
        for nid, node in self.nodes.items():
            if node.status != NodeStatus.PENDING:
                continue
            deps = self.get_dependencies(nid)
            if all(self.nodes[d].status == NodeStatus.SUCCESS for d in deps):
                ready.append(nid)
        return ready


class ExecutionEvent(BaseModel):
    """An event during DAG execution."""
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    node_id: str
    event_type: Literal["started", "completed", "failed", "retrying", "skipped"]
    details: dict[str, Any] = Field(default_factory=dict)


class FailureDecision(BaseModel):
    """Orchestrator's decision on how to handle a failed node."""
    action: Literal["retry", "skip", "abort", "replan"]
    reasoning: str = ""
    # For replan: new DAG or modifications
    modifications: dict[str, Any] = Field(default_factory=dict)


class OrchestratorPlan(BaseModel):
    """Output of the orchestrator agent's planning phase."""
    reasoning: str
    nodes: list[dict[str, Any]]
    edges: list[dict[str, str]]


class HandoffArtifact(BaseModel):
    """
    Structured handoff between agents.
    Each agent's output becomes the next agent's input.
    """
    from_agent: str
    to_agent: str
    content: str = ""                    # Human-readable summary
    file_paths: list[str] = Field(default_factory=list)  # Generated files
    metadata: dict[str, Any] = Field(default_factory=dict)  # Structured data
    created_at: datetime = Field(default_factory=datetime.utcnow)
